name: Trigger Harvest Notification

on:
  # Schedule: runs daily at 7:00 AM IST (1:30 AM UTC)
  schedule:
    - cron: '30 1 * * *'
  
  # Manual trigger from GitHub UI
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Harvest Notification
        run: |
          curl -X POST https://agrigpt-khpr.onrender.com/api/notifications/run-harvest-notifications
